---
- name: Configure logrotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
  when: logrotate_global_config | length

- name: Configure logrotate files
  template:
    src: config_files.j2
    dest: /etc/logrotate.d/{{ item.name }}
  loop: "{{ logrotate_config_files }}"
  when: logrotate_config_files | length
